title: Site Title
description: > # this means to ignore newlines until "baseurl:"
  Description for the website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

company: Company Name #company name that owns/created this site
location: Location #location is used for the Terms of Use & Privacy Policy


# Build settings
markdown: kramdown
exclude: [node_modules]
include: [_pages]
permalink: /posts/:title/