title: Site Title
description: > # this means to ignore newlines until "baseurl:"
  Description for the website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

#Information that is used to create the Terms of Service & Privacy Policy pages
company: Company Name
location: Location
start-year: 2016

# Build settings
markdown: kramdown
exclude: [node_modules, package.json, gulpfile.js, README.md]
include: [_pages]
permalink: /posts/:title/